if (!process.env.BEANSTALK)
  require('dotenv').config()
  
module.exports = {
  BEANSTALK: process.env.BEANSTALK,
  DISCORD_TOKEN: process.env.DISCORD_TOKEN,
  AWS_ACCESS_KEY_ID: process.env.AWS_ACCESS_KEY_ID,
  AWS_SECRET_ACCESS_KEY: process.env.AWS_SECRET_ACCESS_KEY,
  AWS_REGION: process.env.AWS_REGION,
  MATCHES_TABLE: process.env.MATCHES_TABLE,
  NADES_TABLE: process.env.NADES_TABLE,
  GITHUB_REPOSITORY: process.env.GITHUB_REPOSITORY,
  ACTIVITY_REFRESH_INTERVAL_IN_S: process.env.ACTIVITY_REFRESH_INTERVAL_IN_S || 600,
  ALLOWED_SERVERS: process.env.ALLOWED_SERVERS.split('__NEW_LINE__'),
  ALLOWED_DM_USERS: process.env.ALLOWED_DM_USERS.split('__NEW_LINE__'),
  MATCHES_TABLE_MATCH_ID_INDEX: process.env.MATCHES_TABLE_MATCH_ID_INDEX,
  NADES_TABLE_NADE_ID_INDEX: process.env.NADES_TABLE_NADE_ID_INDEX,
  NADES_TABLE_SCANNABLE_INDEX: process.env.NADES_TABLE_SCANNABLE_INDEX,
  GOOGLE_CLIENT_EMAIL: process.env.GOOGLE_CLIENT_EMAIL,
  GOOGLE_PRIVATE_KEY: process.env.GOOGLE_PRIVATE_KEY.replace(/__NEW_LINE__/g, "\n"),
  GOOGLE_PROJECT_ID: process.env.GOOGLE_PROJECT_ID
}